Performance improvements
mysociety/labour-mapit pull request #11
Opened 2023-11-28 09:44 UTC by davea

- Never cache `/uprn` responses
- Add support for a read-only DB replica
- Django 4 upgrade

2023-11-28 10:14 UTC, sagepe commented
Just a thought, and possibly not needed for this stage, but I wondered how easy it would be to support [libpq connection string URIs](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNSTRING), that way we could autodetect which replica was currently the writeable one without it being explicitly specified in config.

2023-11-30 14:09 UTC, dracos requested changes
Think the github action might need an apt-get update first to get that running again.
Other than that, and assuming tests then okay, only one suggestion of nicer Django URL routing :)

2023-11-30 14:09 UTC, dracos commented on mapit_labour/urls.py
> +    re_path(r"^addressbase$", addressbase, name="mapit_labour-addressbase"),
You could also import path and make these use the simpler one, e.g. this one is `path('addressbase')`

2023-12-07 12:39 UTC, dracos approved these changes
⬆️

2023-12-07 14:29 UTC, merged